window.IMPOSTER_SONG_LIBRARY = [
  { title: "Bohemian Rhapsody", artist: "Queen", year: 1975, genre: "rock", difficulty: 1, source: "imposter-known" },
  { title: "Don't Stop Believin'", artist: "Journey", year: 1981, genre: "rock", difficulty: 1, source: "imposter-known" },
  { title: "Sweet Caroline", artist: "Neil Diamond", year: 1969, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Dancing Queen", artist: "ABBA", year: 1976, genre: "disco", difficulty: 1, source: "imposter-known" },
  { title: "Stayin' Alive", artist: "Bee Gees", year: 1977, genre: "disco", difficulty: 1, source: "imposter-known" },
  { title: "September", artist: "Earth, Wind & Fire", year: 1978, genre: "funk", difficulty: 1, source: "imposter-known" },
  { title: "Another One Bites the Dust", artist: "Queen", year: 1980, genre: "rock", difficulty: 1, source: "imposter-known" },
  { title: "Eye of the Tiger", artist: "Survivor", year: 1982, genre: "rock", difficulty: 1, source: "imposter-known" },
  { title: "Africa", artist: "TOTO", year: 1982, genre: "pop-rock", difficulty: 1, source: "imposter-known" },
  { title: "Billie Jean", artist: "Michael Jackson", year: 1982, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Beat It", artist: "Michael Jackson", year: 1982, genre: "pop-rock", difficulty: 1, source: "imposter-known" },
  { title: "Sweet Dreams (Are Made of This)", artist: "Eurythmics", year: 1983, genre: "synth-pop", difficulty: 1, source: "imposter-known" },
  { title: "Take On Me", artist: "a-ha", year: 1985, genre: "synth-pop", difficulty: 1, source: "imposter-known" },
  { title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986, genre: "rock", difficulty: 1, source: "imposter-known" },
  { title: "Never Gonna Give You Up", artist: "Rick Astley", year: 1987, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "I Wanna Dance with Somebody", artist: "Whitney Houston", year: 1987, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991, genre: "grunge", difficulty: 1, source: "imposter-known" },
  { title: "Wonderwall", artist: "Oasis", year: 1995, genre: "britpop", difficulty: 1, source: "imposter-known" },
  { title: "Wannabe", artist: "Spice Girls", year: 1996, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Barbie Girl", artist: "Aqua", year: 1997, genre: "eurodance", difficulty: 1, source: "imposter-known" },
  { title: "My Heart Will Go On", artist: "Celine Dion", year: 1997, genre: "soundtrack", difficulty: 1, source: "imposter-known" },
  { title: "Mambo No. 5", artist: "Lou Bega", year: 1999, genre: "latin-pop", difficulty: 1, source: "imposter-known" },
  { title: "All Star", artist: "Smash Mouth", year: 1999, genre: "pop-rock", difficulty: 1, source: "imposter-known" },
  { title: "Oops!... I Did It Again", artist: "Britney Spears", year: 2000, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "In the End", artist: "Linkin Park", year: 2000, genre: "rock", difficulty: 1, source: "imposter-known" },
  { title: "Lose Yourself", artist: "Eminem", year: 2002, genre: "hip-hop", difficulty: 1, source: "imposter-known" },
  { title: "Crazy in Love", artist: "Beyonce", year: 2003, genre: "rnb-pop", difficulty: 1, source: "imposter-known", searchTerms: ["Crazy in Love Beyonce Jay-Z"] },
  { title: "Hey Ya!", artist: "Outkast", year: 2003, genre: "hip-hop", difficulty: 1, source: "imposter-known" },
  { title: "Mr. Brightside", artist: "The Killers", year: 2003, genre: "indie-rock", difficulty: 1, source: "imposter-known" },
  { title: "Toxic", artist: "Britney Spears", year: 2003, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Yeah!", artist: "Usher", year: 2004, genre: "rnb", difficulty: 1, source: "imposter-known", searchTerms: ["Yeah Usher Lil Jon Ludacris"] },
  { title: "Hips Don't Lie", artist: "Shakira", year: 2005, genre: "latin-pop", difficulty: 1, source: "imposter-known" },
  { title: "Crazy", artist: "Gnarls Barkley", year: 2006, genre: "soul-pop", difficulty: 1, source: "imposter-known" },
  { title: "Umbrella", artist: "Rihanna", year: 2007, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Poker Face", artist: "Lady Gaga", year: 2008, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "I Gotta Feeling", artist: "Black Eyed Peas", year: 2009, genre: "dance-pop", difficulty: 1, source: "imposter-known" },
  { title: "Bad Romance", artist: "Lady Gaga", year: 2009, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Firework", artist: "Katy Perry", year: 2010, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Rolling in the Deep", artist: "Adele", year: 2010, genre: "soul-pop", difficulty: 1, source: "imposter-known" },
  { title: "Somebody That I Used to Know", artist: "Gotye", year: 2011, genre: "indie-pop", difficulty: 1, source: "imposter-known" },
  { title: "Call Me Maybe", artist: "Carly Rae Jepsen", year: 2011, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Gangnam Style", artist: "PSY", year: 2012, genre: "k-pop", difficulty: 1, source: "imposter-known" },
  { title: "Get Lucky", artist: "Daft Punk", year: 2013, genre: "disco-pop", difficulty: 1, source: "imposter-known" },
  { title: "Happy", artist: "Pharrell Williams", year: 2013, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Let It Go", artist: "Idina Menzel", year: 2013, genre: "soundtrack", difficulty: 1, source: "imposter-known" },
  { title: "Shake It Off", artist: "Taylor Swift", year: 2014, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Uptown Funk", artist: "Mark Ronson", year: 2014, genre: "funk-pop", difficulty: 1, source: "imposter-known", searchTerms: ["Uptown Funk Mark Ronson Bruno Mars"] },
  { title: "Hello", artist: "Adele", year: 2015, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Can't Stop the Feeling!", artist: "Justin Timberlake", year: 2016, genre: "soundtrack", difficulty: 1, source: "imposter-known" },
  { title: "Shape of You", artist: "Ed Sheeran", year: 2017, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Despacito", artist: "Luis Fonsi", year: 2017, genre: "latin-pop", difficulty: 1, source: "imposter-known" },
  { title: "Old Town Road", artist: "Lil Nas X", year: 2019, genre: "country-rap", difficulty: 1, source: "imposter-known" },
  { title: "Blinding Lights", artist: "The Weeknd", year: 2019, genre: "synth-pop", difficulty: 1, source: "imposter-known" },
  { title: "Bad Guy", artist: "Billie Eilish", year: 2019, genre: "alt-pop", difficulty: 1, source: "imposter-known" },
  { title: "Dance Monkey", artist: "Tones and I", year: 2019, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Levitating", artist: "Dua Lipa", year: 2020, genre: "dance-pop", difficulty: 1, source: "imposter-known" },
  { title: "As It Was", artist: "Harry Styles", year: 2022, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Flowers", artist: "Miley Cyrus", year: 2023, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "Greased Lightnin'", artist: "John Travolta", year: 1978, genre: "soundtrack", difficulty: 1, source: "imposter-known" },
  { title: "You're the One That I Want", artist: "John Travolta & Olivia Newton-John", year: 1978, genre: "soundtrack", difficulty: 1, source: "imposter-known" },
  { title: "Ghostbusters", artist: "Ray Parker Jr.", year: 1984, genre: "soundtrack", difficulty: 1, source: "imposter-known" },
  { title: "The Power of Love", artist: "Huey Lewis & The News", year: 1985, genre: "soundtrack", difficulty: 1, source: "imposter-known" },
  { title: "Circle of Life", artist: "Carmen Twillie & Lebo M.", year: 1994, genre: "soundtrack", difficulty: 1, source: "imposter-known", searchTerms: ["Circle of Life The Lion King"] },
  { title: "Hakuna Matata", artist: "Nathan Lane, Ernie Sabella, Jason Weaver & Joseph Williams", year: 1994, genre: "soundtrack", difficulty: 1, source: "imposter-known", searchTerms: ["Hakuna Matata The Lion King"] },
  { title: "I'll Make a Man Out of You", artist: "Donny Osmond", year: 1998, genre: "soundtrack", difficulty: 1, source: "imposter-known", searchTerms: ["I'll Make a Man Out of You Mulan"] },
  { title: "A Thousand Miles", artist: "Vanessa Carlton", year: 2002, genre: "pop", difficulty: 1, source: "imposter-known" },
  { title: "I See the Light", artist: "Mandy Moore & Zachary Levi", year: 2010, genre: "soundtrack", difficulty: 1, source: "imposter-known", searchTerms: ["I See the Light Tangled"] },
  { title: "Shallow", artist: "Lady Gaga & Bradley Cooper", year: 2018, genre: "soundtrack", difficulty: 1, source: "imposter-known" },
  { title: "We Don't Talk About Bruno", artist: "Encanto Cast", year: 2021, genre: "soundtrack", difficulty: 1, source: "imposter-known" },
  { title: "Pokemon Theme", artist: "Jason Paige", year: 1998, genre: "tv-theme", difficulty: 1, source: "imposter-known", searchTerms: ["Pokemon Theme Jason Paige Gotta Catch Em All"] },
  { title: "The Fresh Prince of Bel-Air", artist: "DJ Jazzy Jeff & The Fresh Prince", year: 1992, genre: "tv-theme", difficulty: 1, source: "imposter-known", searchTerms: ["Fresh Prince of Bel-Air theme song"] },
  { title: "I'll Be There for You", artist: "The Rembrandts", year: 1995, genre: "tv-theme", difficulty: 1, source: "imposter-known" },
  { title: "Kvinde Min", artist: "Gasolin'", year: 1975, genre: "danish-rock", difficulty: 1, source: "imposter-known" },
  { title: "Midt om natten", artist: "Kim Larsen", year: 1983, genre: "danish-pop", difficulty: 1, source: "imposter-known" },
  { title: "Papirsklip", artist: "Kim Larsen", year: 1983, genre: "danish-pop", difficulty: 1, source: "imposter-known" },
  { title: "Om lidt", artist: "Kim Larsen", year: 1986, genre: "danish-pop", difficulty: 1, source: "imposter-known" },
  { title: "Smuk Som Et Stjerneskud", artist: "Brødrene Olsen", year: 2000, genre: "danish-pop", difficulty: 1, source: "imposter-known" },
  { title: "Barndommens Gade", artist: "Anne Linnet", year: 1986, genre: "danish-pop", difficulty: 1, source: "imposter-known" },
  { title: "Forårsdag", artist: "Anne Linnet", year: 1988, genre: "danish-pop", difficulty: 1, source: "imposter-known" },
  { title: "Vi maler byen rød", artist: "Birthe Kjær", year: 1989, genre: "danish-pop", difficulty: 1, source: "imposter-known" },
  { title: "Danmark", artist: "Shu-bi-dua", year: 1978, genre: "danish-pop", difficulty: 1, source: "imposter-known" },
  { title: "Vilde kaniner", artist: "Gnags", year: 1984, genre: "danish-rock", difficulty: 1, source: "imposter-known" },
  { title: "Fascination", artist: "Alphabeat", year: 2007, genre: "danish-pop", difficulty: 1, source: "imposter-known" },
  { title: "Move Your Feet", artist: "Junior Senior", year: 2002, genre: "danish-dance", difficulty: 1, source: "imposter-known" },
  { title: "From Paris to Berlin", artist: "Infernal", year: 2004, genre: "danish-dance", difficulty: 1, source: "imposter-known" },
  { title: "7 Years", artist: "Lukas Graham", year: 2015, genre: "danish-pop", difficulty: 1, source: "imposter-known" },
  { title: "Drukner I Øjne", artist: "The Minds of 99", year: 2014, genre: "danish-rock", difficulty: 1, source: "imposter-known" },
  { title: "Stor Mand", artist: "Tobias Rahim & Andreas Odbjerg", year: 2021, genre: "danish-pop", difficulty: 1, source: "imposter-known" },
  { title: "Kender Du Det", artist: "Nik & Jay", year: 2002, genre: "danish-pop", difficulty: 1, source: "imposter-known" },
  { title: "Boing!", artist: "Nik & Jay", year: 2004, genre: "danish-pop", difficulty: 1, source: "imposter-known" },
  { title: "Tættere På Himlen", artist: "Burhan G", year: 2010, genre: "danish-pop", difficulty: 1, source: "imposter-known" },
  { title: "Kun For Mig", artist: "Medina", year: 2008, genre: "danish-pop", difficulty: 1, source: "imposter-known" },
  { title: "Gi' Mig Danmark Tilbage", artist: "Natasja", year: 2007, genre: "danish-reggae", difficulty: 1, source: "imposter-known" }
];
